apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036  # Choose a nodePort within the valid range (30000-32767)
  type: NodePort
