name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
          docker build -t tony06/task-api:latest .
          
    - name: Push Docker Image
      run: |
         docker push tony06/task-api:latest

    - name: Kubectl Actions
      uses: tale/kubectl-action@v1
      with: 
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
        working-directory: kubernetes
    - run: |
        kubectl apply -f ./kubernetes/deployment.yml
        kubectl apply -f ./kubernetes/service.yml
        

